<?php

use Illuminate\Database\Seeder;

class LocalidadesTlaxcalaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //

         DB::table('cat_localidad')->insert([


            ['idMunicipio'=>2028,'nombre' =>'AMAXAC DE GUERRERO'],
            ['idMunicipio'=>2028,'nombre' =>'SAN DAMIAN TLACOCALPAN'],
            ['idMunicipio'=>2028,'nombre' =>'LA PRECIOSA [RANCHO]'],
            ['idMunicipio'=>2029,'nombre' =>'APETATITLAN'],
            ['idMunicipio'=>2029,'nombre' =>'BELEN ATZITZIMITITLAN'],
            ['idMunicipio'=>2029,'nombre' =>'SAN MATIAS TEPETOMATITLAN'],
            ['idMunicipio'=>2029,'nombre' =>'TECOLOTLA'],
            ['idMunicipio'=>2029,'nombre' =>'TLATEMPAN'],
            ['idMunicipio'=>2029,'nombre' =>'LA LOMA [COLONIA]'],
            ['idMunicipio'=>2030,'nombre' =>'ATLANGATEPEC'],
            ['idMunicipio'=>2030,'nombre' =>'EX-HACIENDA SAN JOSE ATLANGA'],
            ['idMunicipio'=>2030,'nombre' =>'COLONIA AGRICOLA SAN LUIS'],
            ['idMunicipio'=>2030,'nombre' =>'SAN PEDRO ECATEPEC'],
            ['idMunicipio'=>2030,'nombre' =>'COLONIA AGRICOLA SANTA CLARA OZUMBA'],
            ['idMunicipio'=>2030,'nombre' =>'SANTA MARIA TEPETZALA'],
            ['idMunicipio'=>2030,'nombre' =>'SAN JOSE DE SANTA ROSA ZACAPEXCO'],
            ['idMunicipio'=>2030,'nombre' =>'EX-HACIENDA SAN ANTONIO TEPETZALA'],
            ['idMunicipio'=>2030,'nombre' =>'COLONIA BENITO JUAREZ (TEZOYO)'],
            ['idMunicipio'=>2030,'nombre' =>'LA TRASQUILA'],
            ['idMunicipio'=>2030,'nombre' =>'SANTIAGO VILLALTA'],
            ['idMunicipio'=>2030,'nombre' =>'VISTA HERMOSA'],
            ['idMunicipio'=>2030,'nombre' =>'ZUMPANGO'],
            ['idMunicipio'=>2030,'nombre' =>'EL PARAISO'],
            ['idMunicipio'=>2030,'nombre' =>'LA CAÑADA'],
            ['idMunicipio'=>2030,'nombre' =>'CERRO DE LAS FLORES'],
            ['idMunicipio'=>2030,'nombre' =>'EX-HACIENDA LA TRASQUILA'],
            ['idMunicipio'=>2030,'nombre' =>'EL OCOTAL'],
            ['idMunicipio'=>2030,'nombre' =>'SANTA ELENA'],
            ['idMunicipio'=>2030,'nombre' =>'VILLA DE LAS FLORES'],
            ['idMunicipio'=>2030,'nombre' =>'COLONIA LOMA BONITA'],
            ['idMunicipio'=>2030,'nombre' =>'RANCHO JERICO'],
            ['idMunicipio'=>2030,'nombre' =>'SAN ANTONIO ZACAPEXCO'],
            ['idMunicipio'=>2030,'nombre' =>'XUXTEPEC'],
            ['idMunicipio'=>2030,'nombre' =>'LA FLOR [RANCHO]'],
            ['idMunicipio'=>2030,'nombre' =>'CUARTA FRACCION DE OLIVARES'],
            ['idMunicipio'=>2030,'nombre' =>'LA CUCHILLA (EL ALCANFOR)'],
            ['idMunicipio'=>2030,'nombre' =>'FRACCION SAN PEDRO ECATEPEC'],
            ['idMunicipio'=>2030,'nombre' =>'VILLA QUINTA OLIVARES [CENTRO VACACIONAL]'],
            ['idMunicipio'=>2030,'nombre' =>'RANCHO XALNENE'],
            ['idMunicipio'=>2030,'nombre' =>'LA HERRADURA [RANCHO]'],
            ['idMunicipio'=>2030,'nombre' =>'SAN ANTONIO (LA ESPERANZA)'],
            ['idMunicipio'=>2030,'nombre' =>'SAN JOSE ATLANGA'],
            ['idMunicipio'=>2030,'nombre' =>'TEPEZILAPAN'],
            ['idMunicipio'=>2030,'nombre' =>'TERCERA FRACCION DE OLIVARES'],
            ['idMunicipio'=>2030,'nombre' =>'LA TROJE'],
            ['idMunicipio'=>2030,'nombre' =>'EL CATORCE'],
            ['idMunicipio'=>2030,'nombre' =>'EL HUERFANO'],
            ['idMunicipio'=>2030,'nombre' =>'EL LLANO DE XUXTEPEC'],
            ['idMunicipio'=>2030,'nombre' =>'EL OCOTE'],
            ['idMunicipio'=>2030,'nombre' =>'EL OCOTE (EL JAGÜEY)'],
            ['idMunicipio'=>2030,'nombre' =>'EL ENCINO [RANCHO]'],
            ['idMunicipio'=>2030,'nombre' =>'EL OCOTE [RANCHO]'],
            ['idMunicipio'=>2030,'nombre' =>'EL POTRERO [RANCHO]'],
            ['idMunicipio'=>2030,'nombre' =>'LAS BARRANCAS [RANCHO]'],
            ['idMunicipio'=>2030,'nombre' =>'LAS TINAJAS [RANCHO]'],
            ['idMunicipio'=>2030,'nombre' =>'LOS CAPULINES [RANCHO]'],
            ['idMunicipio'=>2030,'nombre' =>'LOS ENCINOS [RANCHO]'],
            ['idMunicipio'=>2030,'nombre' =>'LOS NOPALITOS [RANCHO]'],
            ['idMunicipio'=>2030,'nombre' =>'SAN SIMON'],
            ['idMunicipio'=>2030,'nombre' =>'LAS TINAJAS (LA TEPOZANERA)'],
            ['idMunicipio'=>2030,'nombre' =>'LUIS ECHEVERRIA [ESTABLO BOVINO]'],
            ['idMunicipio'=>2030,'nombre' =>'EL MIRADOR'],
            ['idMunicipio'=>2030,'nombre' =>'LA PROVIDENCIA'],
            ['idMunicipio'=>2030,'nombre' =>'SAMUEL OREA (RANCHO EL PATO)'],
            ['idMunicipio'=>2030,'nombre' =>'LA JOYA'],
            ['idMunicipio'=>2030,'nombre' =>'RANCHO GUADALUPE'],
            ['idMunicipio'=>2030,'nombre' =>'UNIDAD HABITACIONAL I'],
            ['idMunicipio'=>2030,'nombre' =>'ALMEYA'],
            ['idMunicipio'=>2030,'nombre' =>'EL CAPRICHO'],
            ['idMunicipio'=>2030,'nombre' =>'EL COLIBRI'],
            ['idMunicipio'=>2030,'nombre' =>'EL HERRADERO'],
            ['idMunicipio'=>2030,'nombre' =>'LA VACA PRIETA'],
            ['idMunicipio'=>2030,'nombre' =>'LOS CUATRO HERMANOS [RANCHO]'],
            ['idMunicipio'=>2030,'nombre' =>'SAN PEDRO ZACAPEXCO'],
            ['idMunicipio'=>2030,'nombre' =>'LOS TRES POCILLOS'],
            ['idMunicipio'=>2030,'nombre' =>'CAMINO REAL'],
            ['idMunicipio'=>2030,'nombre' =>'JESUS GARCIA'],
            ['idMunicipio'=>2030,'nombre' =>'TERCERA SECCION DE BAIVER'],
            ['idMunicipio'=>2031,'nombre' =>'ATLZAYANCA'],
            ['idMunicipio'=>2031,'nombre' =>'SAN FRANCISCO AXOPILCO'],
            ['idMunicipio'=>2031,'nombre' =>'SAN JOSE BUENAVISTA'],
            ['idMunicipio'=>2031,'nombre' =>'CONCEPCION HIDALGO'],
            ['idMunicipio'=>2031,'nombre' =>'FELIPE CARRILLO PUERTO'],
            ['idMunicipio'=>2031,'nombre' =>'LA GARITA'],
            ['idMunicipio'=>2031,'nombre' =>'LAZARO CARDENAS'],
            ['idMunicipio'=>2031,'nombre' =>'MESA REDONDA'],
            ['idMunicipio'=>2031,'nombre' =>'MIAHUAPAN EL BAJO'],
            ['idMunicipio'=>2031,'nombre' =>'NEXNOPALA'],
            ['idMunicipio'=>2031,'nombre' =>'RANCHO OCOTLA'],
            ['idMunicipio'=>2031,'nombre' =>'LA RINCONA'],
            ['idMunicipio'=>2031,'nombre' =>'SAN ANTONIO TECOPILCO'],
            ['idMunicipio'=>2031,'nombre' =>'SAN JOSE XALASCO'],
            ['idMunicipio'=>2031,'nombre' =>'SAN JUAN OCOTITLA'],
            ['idMunicipio'=>2031,'nombre' =>'SANTA CRUZ POCITOS'],
            ['idMunicipio'=>2031,'nombre' =>'SANTA MARIA LAS CUEVAS'],
            ['idMunicipio'=>2031,'nombre' =>'XALTITLA'],
            ['idMunicipio'=>2031,'nombre' =>'COLONIA DELICIAS'],
            ['idMunicipio'=>2031,'nombre' =>'SAN JOSE PILANCON'],
            ['idMunicipio'=>2031,'nombre' =>'RANCHO BLANCO'],
            ['idMunicipio'=>2031,'nombre' =>'RANCHERIA DE POCITOS'],
            ['idMunicipio'=>2031,'nombre' =>'SANTA MARTHA [RANCHO]'],
            ['idMunicipio'=>2031,'nombre' =>'CARRETA'],
            ['idMunicipio'=>2031,'nombre' =>'XARERO XALTITLA'],
            ['idMunicipio'=>2031,'nombre' =>'MAZEHUALPA'],
            ['idMunicipio'=>2031,'nombre' =>'LOMA DE JUNGUITO'],
            ['idMunicipio'=>2031,'nombre' =>'SAN MIGUEL FRANCO [RANCHERIA]'],
            ['idMunicipio'=>2031,'nombre' =>'MIAHUAPAN EL ALTO'],
            ['idMunicipio'=>2031,'nombre' =>'COLONIA NAZARETH'],
            ['idMunicipio'=>2031,'nombre' =>'SAN JOSE MIRAVALLE'],
            ['idMunicipio'=>2031,'nombre' =>'SANTA CRUZ [RANCHO]'],
            ['idMunicipio'=>2031,'nombre' =>'FRACCION CERON (TONALACO)'],
            ['idMunicipio'=>2031,'nombre' =>'LA SOLEDAD LOMA DE OCOTLA [RANCHERIA]'],
            ['idMunicipio'=>2031,'nombre' =>'AMPARITO'],
            ['idMunicipio'=>2031,'nombre' =>'LOS OCALITOS'],
            ['idMunicipio'=>2031,'nombre' =>'MARIANO GUARNEROS ARROYO'],
            ['idMunicipio'=>2031,'nombre' =>'AURELIO AGUILAR'],
            ['idMunicipio'=>2031,'nombre' =>'FRACCION CERON'],
            ['idMunicipio'=>2031,'nombre' =>'JOSE FERNANDEZ'],
            ['idMunicipio'=>2031,'nombre' =>'SAN JERONIMO ZACUALPAN'],
            ['idMunicipio'=>2031,'nombre' =>'TECHACHALCO'],
            ['idMunicipio'=>2031,'nombre' =>'HUERTA LIZET'],
            ['idMunicipio'=>2031,'nombre' =>'SAN MIGUEL'],
            ['idMunicipio'=>2031,'nombre' =>'SANTO DOMINGO'],
            ['idMunicipio'=>2031,'nombre' =>'SAN ANTONIO [BARRIO]'],
            ['idMunicipio'=>2032,'nombre' =>'CIUDAD DE APIZACO'],
            ['idMunicipio'=>2032,'nombre' =>'CERRITO DE GUADALUPE'],
            ['idMunicipio'=>2032,'nombre' =>'GUADALUPE TEXCALAC'],
            ['idMunicipio'=>2032,'nombre' =>'JAGÜEY PRIETO'],
            ['idMunicipio'=>2032,'nombre' =>'JOSE MARIA MORELOS'],
            ['idMunicipio'=>2032,'nombre' =>'COLONIA SAN ISIDRO'],
            ['idMunicipio'=>2032,'nombre' =>'SAN LUIS APIZAQUITO'],
            ['idMunicipio'=>2032,'nombre' =>'SANTA ANITA HUILOAC'],
            ['idMunicipio'=>2032,'nombre' =>'SANTA MARIA TEXCALAC'],
            ['idMunicipio'=>2032,'nombre' =>'ACTIPAN'],
            ['idMunicipio'=>2032,'nombre' =>'ATENCO'],
            ['idMunicipio'=>2032,'nombre' =>'EJIDO DE SAN DIONISIO'],
            ['idMunicipio'=>2032,'nombre' =>'LOS GEMELOS [RANCHO]'],
            ['idMunicipio'=>2032,'nombre' =>'PARADA DE LA VIRGEN'],
            ['idMunicipio'=>2032,'nombre' =>'SAN JOSE TETEL (LA QUEBRADORA)'],
            ['idMunicipio'=>2032,'nombre' =>'FRANCISCO MORENO MORALES'],
            ['idMunicipio'=>2032,'nombre' =>'CUARTA MANZANA'],
            ['idMunicipio'=>2032,'nombre' =>'TOCHAC'],
            ['idMunicipio'=>2032,'nombre' =>'LA VIA (COLONIA EL SILBATO)'],
            ['idMunicipio'=>2032,'nombre' =>'UNIDAD DEPORTIVA'],
            ['idMunicipio'=>2032,'nombre' =>'FRACCIONAMIENTO JARDINES DE SAN FRANCISCO'],
            ['idMunicipio'=>2032,'nombre' =>'CUARTA SECCION'],
            ['idMunicipio'=>2032,'nombre' =>'EJIDO DE SANTA ÚRSULA'],
            ['idMunicipio'=>2032,'nombre' =>'PRIMERA SECCION'],
            ['idMunicipio'=>2033,'nombre' =>'CALPULALPAN'],
            ['idMunicipio'=>2033,'nombre' =>'AMANTLA'],
            ['idMunicipio'=>2033,'nombre' =>'COECILLOS'],
            ['idMunicipio'=>2033,'nombre' =>'EL CARMEN'],
            ['idMunicipio'=>2033,'nombre' =>'MAZAPA'],
            ['idMunicipio'=>2033,'nombre' =>'SAN BARTOLOME DEL MONTE'],
            ['idMunicipio'=>2033,'nombre' =>'SAN CRISTOBAL ZACACALCO'],
            ['idMunicipio'=>2033,'nombre' =>'SAN FELIPE SULTEPEC'],
            ['idMunicipio'=>2033,'nombre' =>'LOS TRES HERMANOS'],
            ['idMunicipio'=>2033,'nombre' =>'SAN MARCOS GUAQUILPAN'],
            ['idMunicipio'=>2033,'nombre' =>'SAN MATEO ATICPAC'],
            ['idMunicipio'=>2033,'nombre' =>'SANTA CATALINA'],
            ['idMunicipio'=>2033,'nombre' =>'SANTIAGO CUAULA'],
            ['idMunicipio'=>2033,'nombre' =>'LA SOLEDAD'],
            ['idMunicipio'=>2033,'nombre' =>'NCPE GUSTAVO DIAZ ORDAZ'],
            ['idMunicipio'=>2033,'nombre' =>'LOS PALACIOS'],
            ['idMunicipio'=>2033,'nombre' =>'SAN JUAN TEMAZCALES'],
            ['idMunicipio'=>2033,'nombre' =>'SANTA CRUZ'],
            ['idMunicipio'=>2033,'nombre' =>'SANTA TERESA'],
            ['idMunicipio'=>2033,'nombre' =>'LA VENTA'],
            ['idMunicipio'=>2033,'nombre' =>'SAN JOSE'],
            ['idMunicipio'=>2033,'nombre' =>'LOS PINOS'],
            ['idMunicipio'=>2033,'nombre' =>'HERMANOS GARCIA'],
            ['idMunicipio'=>2033,'nombre' =>'MONTE DE SAN AGUSTIN'],
            ['idMunicipio'=>2033,'nombre' =>'RANCHO HERMENEGILDO'],
            ['idMunicipio'=>2033,'nombre' =>'LAS DALIAS'],
            ['idMunicipio'=>2033,'nombre' =>'SANTA FELIX'],
            ['idMunicipio'=>2033,'nombre' =>'LOS DIAZ'],
            ['idMunicipio'=>2033,'nombre' =>'JUAN MORALES (LA VENTILLA)'],
            ['idMunicipio'=>2033,'nombre' =>'LA VENTILLA'],
            ['idMunicipio'=>2033,'nombre' =>'EL MIRADOR'],
            ['idMunicipio'=>2033,'nombre' =>'LOS MOGOTES'],
            ['idMunicipio'=>2033,'nombre' =>'LA QUEBRADORA'],
            ['idMunicipio'=>2033,'nombre' =>'POZO SAN VICENTE [RESTAURANTE]'],
            ['idMunicipio'=>2033,'nombre' =>'DAVID SANCHEZ'],
            ['idMunicipio'=>2033,'nombre' =>'LOS MEJIA'],
            ['idMunicipio'=>2033,'nombre' =>'EL CACALOTE'],
            ['idMunicipio'=>2033,'nombre' =>'LA PALMA'],
            ['idMunicipio'=>2033,'nombre' =>'LA HONDONADA'],
            ['idMunicipio'=>2033,'nombre' =>'RANCHO CACHO'],
            ['idMunicipio'=>2033,'nombre' =>'LAS AURAS'],
            ['idMunicipio'=>2033,'nombre' =>'LA FLOR'],
            ['idMunicipio'=>2033,'nombre' =>'EL ROSARIO (PARADA LA CAPILLA)'],
            ['idMunicipio'=>2033,'nombre' =>'LA BLANCA'],
            ['idMunicipio'=>2033,'nombre' =>'PUENTE DEL OCOMIQUE'],
            ['idMunicipio'=>2033,'nombre' =>'DON RAMON'],
            ['idMunicipio'=>2033,'nombre' =>'EL CARMEN [RANCHO]'],
            ['idMunicipio'=>2033,'nombre' =>'MARCELINO CRUZ'],
            ['idMunicipio'=>2033,'nombre' =>'LA MORENA'],
            ['idMunicipio'=>2033,'nombre' =>'LOMA BONITA'],
            ['idMunicipio'=>2033,'nombre' =>'RAYMUNDO ÁLVAREZ GUERRERO'],
            ['idMunicipio'=>2033,'nombre' =>'RANCHO BONITO'],
            ['idMunicipio'=>2033,'nombre' =>'RANCHO DEL VENADO'],
            ['idMunicipio'=>2033,'nombre' =>'SAN MIGUEL'],
            ['idMunicipio'=>2033,'nombre' =>'SAN VICENTE'],
            ['idMunicipio'=>2033,'nombre' =>'SAN ANTONIO (SAN PEDRO)'],
            ['idMunicipio'=>2033,'nombre' =>'CAMINO A SAN VICENTE'],
            ['idMunicipio'=>2033,'nombre' =>'JOSE DIAZ'],
            ['idMunicipio'=>2033,'nombre' =>'LOMA DE SAN AGUSTIN'],
            ['idMunicipio'=>2033,'nombre' =>'ALEJANDRO HERNANDEZ'],
            ['idMunicipio'=>2033,'nombre' =>'LA OCOTERA [RANCHO]'],
            ['idMunicipio'=>2033,'nombre' =>'DOLORES'],
            ['idMunicipio'=>2033,'nombre' =>'EL CONVENTO DE LA SOLEDAD'],
            ['idMunicipio'=>2033,'nombre' =>'EL DURAZNO'],
            ['idMunicipio'=>2033,'nombre' =>'ERNESTO ALONSO'],
            ['idMunicipio'=>2033,'nombre' =>'ESPERANZA ORTIZ'],
            ['idMunicipio'=>2033,'nombre' =>'GABRIEL ROLDAN'],
            ['idMunicipio'=>2033,'nombre' =>'GRANJA DEL POZO'],
            ['idMunicipio'=>2033,'nombre' =>'SAN RODRIGO'],
            ['idMunicipio'=>2033,'nombre' =>'JUAN HERNANDEZ (RANCHO EL SOLITARIO)'],
            ['idMunicipio'=>2033,'nombre' =>'LAS PALOMAS'],
            ['idMunicipio'=>2033,'nombre' =>'SAN PEDRO'],
            ['idMunicipio'=>2033,'nombre' =>'RODOLFO ÁVILA'],
            ['idMunicipio'=>2033,'nombre' =>'SAMUEL LABASTIDA'],
            ['idMunicipio'=>2033,'nombre' =>'EL TRIANGULO'],
            ['idMunicipio'=>2033,'nombre' =>'ÁNGEL PELCASTRE'],
            ['idMunicipio'=>2033,'nombre' =>'HERMANOS ÁVILA'],
            ['idMunicipio'=>2033,'nombre' =>'JACARANDAS'],
            ['idMunicipio'=>2033,'nombre' =>'EL MIRADOR DOS'],
            ['idMunicipio'=>2033,'nombre' =>'ANALCO DOS'],
            ['idMunicipio'=>2033,'nombre' =>'SANTA ROSA'],
            ['idMunicipio'=>2033,'nombre' =>'COLA DEL POTRERO'],
            ['idMunicipio'=>2033,'nombre' =>'PACHECO (DE LA ROSA)'],
            ['idMunicipio'=>2033,'nombre' =>'SAN JUAN DE LOS LAGOS'],
            ['idMunicipio'=>2033,'nombre' =>'SANTA ISABEL MIXTITLAN'],
            ['idMunicipio'=>2033,'nombre' =>'EMILIO LOPEZ'],
            ['idMunicipio'=>2033,'nombre' =>'JUAN ZAVALA'],
            ['idMunicipio'=>2033,'nombre' =>'PARADOR KILOMETRO 57'],
            ['idMunicipio'=>2033,'nombre' =>'SAN FRANCISCO'],
            ['idMunicipio'=>2033,'nombre' =>'EL PIÑON'],
            ['idMunicipio'=>2033,'nombre' =>'ALBINO ALONSO'],
            ['idMunicipio'=>2033,'nombre' =>'LAS TRES V'],
            ['idMunicipio'=>2033,'nombre' =>'LOS POTRILLOS [RANCHO]'],
            ['idMunicipio'=>2033,'nombre' =>'SAN JUAN [RANCHO]'],
            ['idMunicipio'=>2033,'nombre' =>'LA ESPERANZA'],
            ['idMunicipio'=>2033,'nombre' =>'EL ÁLAMO'],
            ['idMunicipio'=>2033,'nombre' =>'ARTURO OLMEDO'],
            ['idMunicipio'=>2033,'nombre' =>'HOSPITAL GENERAL DE CALPULALPAN'],
            ['idMunicipio'=>2033,'nombre' =>'PARADA COECILLOS'],
            ['idMunicipio'=>2033,'nombre' =>'EL REGALO [RANCHO]'],
            ['idMunicipio'=>2033,'nombre' =>'RANCHO ESCONDIDO'],
            ['idMunicipio'=>2033,'nombre' =>'RANCHO PAJARITOS'],
            ['idMunicipio'=>2033,'nombre' =>'SAN ALEJANDRO [RANCHO]'],
            ['idMunicipio'=>2034,'nombre' =>'VILLA DE EL CARMEN TEQUEXQUITLA'],
            ['idMunicipio'=>2034,'nombre' =>'LA SOLEDAD'],
            ['idMunicipio'=>2034,'nombre' =>'OCOTLAN TEMALACAYUCAN'],
            ['idMunicipio'=>2034,'nombre' =>'COLONIA VICENTE GUERRERO'],
            ['idMunicipio'=>2034,'nombre' =>'BARRIO DE GUADALUPE'],
            ['idMunicipio'=>2035,'nombre' =>'CUAPIAXTLA'],
            ['idMunicipio'=>2035,'nombre' =>'LA ASUNCION RASCONA'],
            ['idMunicipio'=>2035,'nombre' =>'EGIPTO'],
            ['idMunicipio'=>2035,'nombre' =>'COLONIA IGNACIO ALLENDE'],
            ['idMunicipio'=>2035,'nombre' =>'COLONIA JOSE MARIA MORELOS'],
            ['idMunicipio'=>2035,'nombre' =>'COLONIA MANUEL ÁVILA CAMACHO'],
            ['idMunicipio'=>2035,'nombre' =>'PLAN DE AYALA'],
            ['idMunicipio'=>2035,'nombre' =>'EX-HACIENDA SAN FRANCISCO CUEXCOMATEPEC'],
            ['idMunicipio'=>2035,'nombre' =>'SAN FRANCISCO CUEXCONTZI'],
            ['idMunicipio'=>2035,'nombre' =>'SAN FELIPE TEOMETITLA'],
            ['idMunicipio'=>2035,'nombre' =>'RANCHO MAZARRAZA'],
            ['idMunicipio'=>2035,'nombre' =>'SAN MIGUEL TEOMETITLA'],
            ['idMunicipio'=>2035,'nombre' =>'SANTA FE UNO'],
            ['idMunicipio'=>2035,'nombre' =>'EL TEJOCOTE'],
            ['idMunicipio'=>2035,'nombre' =>'COLONIA LOMA BONITA'],
            ['idMunicipio'=>2035,'nombre' =>'SAN RAFAEL TEPATLAXCO (UNION Y PROGRESO)'],
            ['idMunicipio'=>2035,'nombre' =>'SANTA BEATRIZ LA NUEVA'],
            ['idMunicipio'=>2035,'nombre' =>'SANTA REBECA'],
            ['idMunicipio'=>2035,'nombre' =>'SAN DIEGO COYOTEPEC'],
            ['idMunicipio'=>2035,'nombre' =>'COLONIA DEL VALLE'],
            ['idMunicipio'=>2035,'nombre' =>'GRANJA DE GUADALUPE'],
            ['idMunicipio'=>2035,'nombre' =>'FRACCION CERON'],
            ['idMunicipio'=>2035,'nombre' =>'TECOAC [GRANJA PORCINA]'],
            ['idMunicipio'=>2035,'nombre' =>'COLONIA NAZARETH'],
            ['idMunicipio'=>2035,'nombre' =>'EJIDO DE ALLENDE'],
            ['idMunicipio'=>2035,'nombre' =>'LA GRANJA (CAMINO A FRANCO)'],
            ['idMunicipio'=>2035,'nombre' =>'PALMA DE TRES BRAZOS (FRACCION SANTO DOMINGO)'],
            ['idMunicipio'=>2035,'nombre' =>'RANCHO CERON'],
            ['idMunicipio'=>2035,'nombre' =>'FACTOR FELIX LOPEZ'],
            ['idMunicipio'=>2036,'nombre' =>'CUAXOMULCO'],
            ['idMunicipio'=>2036,'nombre' =>'SAN MIGUEL BUENAVISTA'],
            ['idMunicipio'=>2036,'nombre' =>'SAN LORENZO XALTELULCO'],
            ['idMunicipio'=>2036,'nombre' =>'ZACAMOLPA'],
            ['idMunicipio'=>2036,'nombre' =>'COXTLA'],
            ['idMunicipio'=>2036,'nombre' =>'TECOLA'],
            
            ['idMunicipio'=>2028,'nombre' =>'SIN INFORMACION'],
            ['idMunicipio'=>2029,'nombre' =>'SIN INFORMACION'],
            ['idMunicipio'=>2030,'nombre' =>'SIN INFORMACION'],
            ['idMunicipio'=>2031,'nombre' =>'SIN INFORMACION'],
            ['idMunicipio'=>2032,'nombre' =>'SIN INFORMACION'],
            ['idMunicipio'=>2033,'nombre' =>'SIN INFORMACION'],
            ['idMunicipio'=>2034,'nombre' =>'SIN INFORMACION'],
            ['idMunicipio'=>2035,'nombre' =>'SIN INFORMACION'],
            ['idMunicipio'=>2036,'nombre' =>'SIN INFORMACION']

 	 	]);




    }
}
