<?php

use Illuminate\Database\Seeder;

class TipoVehiculoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('cat_tipo_vehiculo')->insert([
            ['id'=>  1,'idClaseVehiculo'=>  99,'nombre' => 'CONVERTIBLE'],
            ['id'=>  2,'idClaseVehiculo'=>  99,'nombre' => 'COUPE'],
            ['id'=>  3,'idClaseVehiculo'=>  99,'nombre' => 'LIMOUSINE'],
            ['id'=>  4,'idClaseVehiculo'=>  99,'nombre' => 'SEDAN'],
            ['id'=>  5,'idClaseVehiculo'=>  99,'nombre' => 'SPORT'],
            ['id'=>  6,'idClaseVehiculo'=>  99,'nombre' => 'VAGONETA'],
            ['id'=>  7,'idClaseVehiculo'=>  1,'nombre' => 'COMBI'],
            ['id'=>  8,'idClaseVehiculo'=>  7,'nombre' => 'OTROS'],
            ['id'=>  9,'idClaseVehiculo'=>  2,'nombre' => 'AUTO TANQUE'],
            ['id'=> 10,'idClaseVehiculo'=>  2,'nombre' => 'CABINA'],
            ['id'=> 11,'idClaseVehiculo'=>  2,'nombre' => 'CAJA'],
            ['id'=> 12,'idClaseVehiculo'=>  2,'nombre' => 'CASETA'],
            ['id'=> 13,'idClaseVehiculo'=>  99,'nombre' => 'JEEP'],
            ['id'=> 14,'idClaseVehiculo'=>  2,'nombre' => 'CELDILLAS'],
            ['id'=> 15,'idClaseVehiculo'=>  2,'nombre' => 'CHASIS'],
            ['id'=> 16,'idClaseVehiculo'=>  2,'nombre' => 'ESTACAS'],
            ['id'=> 17,'idClaseVehiculo'=>  4,'nombre' => 'MICROBUS'],
            ['id'=> 18,'idClaseVehiculo'=>  4,'nombre' => 'OMNIBUS'],
            ['id'=> 19,'idClaseVehiculo'=>  2,'nombre' => 'PANEL'],
            ['id'=> 20,'idClaseVehiculo'=>  2,'nombre' => 'PICK UP'],
            ['id'=> 21,'idClaseVehiculo'=>  2,'nombre' => 'PIPA'],
            ['id'=> 22,'idClaseVehiculo'=>  2,'nombre' => 'PLATAFORMA'],
            ['id'=> 23,'idClaseVehiculo'=>  2,'nombre' => 'REDILAS'],
            ['id'=> 24,'idClaseVehiculo'=>  2,'nombre' => 'REFRIGERADOR'],
            ['id' => 25, 'idClaseVehiculo'  => 2, 'nombre' => 'TANQUE'],
            ['id' => 26, 'idClaseVehiculo'  => 9, 'nombre' => 'TRACTOR'],
            ['id' => 27, 'idClaseVehiculo'  => 2, 'nombre' => 'VANETTE'],
            ['id' => 28, 'idClaseVehiculo'  => 2, 'nombre' => 'VOLTEO'],
            ['id' => 30, 'idClaseVehiculo'  => 99, 'nombre' => 'AUTOMOVILES'],
            ['id' => 31, 'idClaseVehiculo'  => 5, 'nombre' => 'DOLLY'],
            ['id' => 32, 'idClaseVehiculo'  => 5, 'nombre' => 'HABITACION'],
            ['id' => 33, 'idClaseVehiculo'  => 5, 'nombre' => 'INDUSTRIAL'],
            ['id' => 34, 'idClaseVehiculo'  => 5, 'nombre' => 'JAULA'],
            ['id' => 37, 'idClaseVehiculo'  => 7, 'nombre' => 'TANQUES (R) O (S)'],
            ['id' => 38, 'idClaseVehiculo'  => 7, 'nombre' => 'AMBULANCIA'],
            ['id' => 39, 'idClaseVehiculo'  => 7, 'nombre' => 'CARROZA'],
            ['id' => 40, 'idClaseVehiculo'  => 7, 'nombre' => 'EQUIPO ESPECIAL'],
            ['id' => 41, 'idClaseVehiculo'  => 7, 'nombre' => 'GRUA'],
            ['id' => 42, 'idClaseVehiculo'  => 9, 'nombre' => 'REVOLVEDORA'],
            ['id' => 44, 'idClaseVehiculo'  => 6, 'nombre' => 'MOTO'],
            ['id' => 45, 'idClaseVehiculo'  => 1, 'nombre' => 'CAMIONETA'],
            ['id' => 46, 'idClaseVehiculo'  => 7, 'nombre' => 'TAXI'],
            ['id' => 66, 'idClaseVehiculo'  => 2, 'nombre' => 'TRACTOCAMION'],
            ['id' => 88, 'idClaseVehiculo'  => 1, 'nombre' => 'MINIVAN'],
            ['id' => 99, 'idClaseVehiculo'  => 2, 'nombre' => 'CAMIONES'],
            ['id' => 100, 'idClaseVehiculo'  => 7, 'nombre' => 'BICITAXI'],
            ['id' => 101, 'idClaseVehiculo'  => 1, 'nombre' => 'BLAZER'],
            ['id' => 102, 'idClaseVehiculo'  => 1, 'nombre' => 'BRONCO'],
            ['id' => 103, 'idClaseVehiculo'  => 1, 'nombre' => 'CARRY ALL'],
            ['id' => 104, 'idClaseVehiculo'  => 1, 'nombre' => 'CHARGER'],
            ['id' => 105, 'idClaseVehiculo'  => 6, 'nombre' => 'CUATRIMOTO'],
            ['id' => 106, 'idClaseVehiculo'  => 99, 'nombre' => 'GUAYIN'],
            ['id' => 107, 'idClaseVehiculo'  => 99, 'nombre' => 'HARD TOP'],
            ['id' => 108, 'idClaseVehiculo'  => 99, 'nombre' => 'HATCH BACK'],
            ['id' => 109, 'idClaseVehiculo'  => 6, 'nombre' => 'MINIMOTO'],
            ['id' => 110, 'idClaseVehiculo'  => 6, 'nombre' => 'MOTOCARRO'],
            ['id' => 111, 'idClaseVehiculo'  => 6, 'nombre' => 'MOTOCICLETA'],
            ['id' => 112, 'idClaseVehiculo'  => 5, 'nombre' => 'REMOLQUES'],
            ['id' => 113, 'idClaseVehiculo'  => 2, 'nombre' => 'TORTON'],
            ['id' => 114, 'idClaseVehiculo'  => 99, 'nombre' => 'AVIONETA'],
            ['id' => 115, 'idClaseVehiculo'  => 99, 'nombre' => 'DEMOSTRADORA'],
            ['id' => 116, 'idClaseVehiculo'  => 99, 'nombre' => 'HELICOPTERO'],
            ['id' => 117, 'idClaseVehiculo'  => 99, 'nombre' => 'JET-SKI'],
            ['id' => 118, 'idClaseVehiculo'  => 99, 'nombre' => 'LANCHA'],
            ['id' => 119, 'idClaseVehiculo'  => 99, 'nombre' => 'MAQUINA DE TREN'],
            ['id' => 120, 'idClaseVehiculo'  => 99, 'nombre' => 'MINIBUS'],
            ['id' => 121, 'idClaseVehiculo'  => 99, 'nombre' => 'MUDANZA'],
            ['id' => 122, 'idClaseVehiculo'  => 99, 'nombre' => 'QUINTA RUEDA'],
            ['id' => 123, 'idClaseVehiculo'  => 99, 'nombre' => 'VAGON DEL TREN'],
            ['id' => 126, 'idClaseVehiculo'  => 99, 'nombre' => 'SILVERADO'],
            ['id' => 127, 'idClaseVehiculo'  => 99, 'nombre' => 'SLE'],
            ['id' => 128, 'idClaseVehiculo'  => 99, 'nombre' => 'SUBURBAN'],
            ['id' => 129, 'idClaseVehiculo'  => 99, 'nombre' => 'TOWN COUNTRY'],
            ['id' => 130, 'idClaseVehiculo'  => 99, 'nombre' => 'AUTOMOVIL PASAJEROS'],
            ['id' => 133, 'idClaseVehiculo'  => 99, 'nombre' => 'AUTOBUS'],
            ['id' => 134, 'idClaseVehiculo'  => 7, 'nombre' => 'PATRULLA'],
            ['id' => 135, 'idClaseVehiculo'  => 99, 'nombre' => 'STAND DE TIRO MOVIL'],
            ['id' => 136, 'idClaseVehiculo'  => 99, 'nombre' => 'LABORATORIO MOVIL'],
            ['id' => 137, 'idClaseVehiculo'  => 1, 'nombre' => 'VAM'],
            ['id' => 138, 'idClaseVehiculo'  => 1, 'nombre' => 'FAST BACK'],
            ['id' => 139, 'idClaseVehiculo'  => 1, 'nombre' => 'STATE'],
            ['id' => 140, 'idClaseVehiculo'  => 1, 'nombre' => 'STATION WAGON'],
            ['id' => 141, 'idClaseVehiculo'  => 1, 'nombre' => 'TODO TERRENO 4X4'],
            ['id' => 142, 'idClaseVehiculo'  => 2, 'nombre' => 'FURGONETA'],
            ['id' => 143, 'idClaseVehiculo'  => 2, 'nombre' => 'SUV'],
            ['id' => 144, 'idClaseVehiculo'  => 2, 'nombre' => 'MPV'],
            ['id' => 145, 'idClaseVehiculo'  => 2, 'nombre' => 'RCV'],
            ['id' => 146, 'idClaseVehiculo'  => 2, 'nombre' => 'VAN'],
            ['id' => 147, 'idClaseVehiculo'  => 5, 'nombre' => 'PIPA'],
            ['id' => 148, 'idClaseVehiculo'  => 2, 'nombre' => 'TODO TERRENO 4X4'],
            ['id' => 149, 'idClaseVehiculo'  => 5, 'nombre' => 'TANQUE'],
            ['id' => 150, 'idClaseVehiculo'  => 4, 'nombre' => 'METROBUS'],
            ['id' => 151, 'idClaseVehiculo'  => 5, 'nombre' => 'PLATAFORMA'],
            ['id' => 152, 'idClaseVehiculo'  => 5, 'nombre' => 'CAJA'],
            ['id' => 153, 'idClaseVehiculo'  => 5, 'nombre' => 'REFRIGERADOR'],
            ['id' => 154, 'idClaseVehiculo'  => 5, 'nombre' => 'GRANELERO'],
            ['id' => 155, 'idClaseVehiculo'  => 5, 'nombre' => 'TOLVA'],
            ['id' => 156, 'idClaseVehiculo'  => 5, 'nombre' => 'VOLTEO'],
            ['id' => 157, 'idClaseVehiculo'  => 6, 'nombre' => 'MOTOCROSS'],
            ['id' => 158, 'idClaseVehiculo'  => 6, 'nombre' => 'PONY'],
            ['id' => 159, 'idClaseVehiculo'  => 6, 'nombre' => 'ENDURO'],
            ['id' => 160, 'idClaseVehiculo'  => 6, 'nombre' => 'TRIAL'],
            ['id' => 161, 'idClaseVehiculo'  => 6, 'nombre' => 'CRUISER'],
            ['id' => 162, 'idClaseVehiculo'  => 6, 'nombre' => 'SPORTBIKE'],
            ['id' => 163, 'idClaseVehiculo'  => 6, 'nombre' => 'STREETBIKE'],
            ['id' => 164, 'idClaseVehiculo'  => 6, 'nombre' => 'DUAL'],
            ['id' => 165, 'idClaseVehiculo'  => 6, 'nombre' => 'TRABAJO'],
            ['id' => 166, 'idClaseVehiculo'  => 9, 'nombre' => 'RETROEXCAVADORA'],
            ['id' => 167, 'idClaseVehiculo'  => 9, 'nombre' => 'EXCAVADORA'],
            ['id' => 168, 'idClaseVehiculo'  => 9, 'nombre' => 'MOTOCONFORMADORA'],
            ['id' => 169, 'idClaseVehiculo'  => 9, 'nombre' => 'CARGADOR'],
            ['id' => 170, 'idClaseVehiculo'  => 9, 'nombre' => 'MINICARGADOR'],
            ['id' => 171, 'idClaseVehiculo'  => 9, 'nombre' => 'TRASCABO'],
            ['id' => 172, 'idClaseVehiculo'  => 9, 'nombre' => 'COMPACTADOR'],
            ['id' => 173, 'idClaseVehiculo'  => 9, 'nombre' => 'MONTACARGAS'],
            ['id' => 174, 'idClaseVehiculo'  => 5, 'nombre' => 'REDILAS'],
            ['id' => 175, 'idClaseVehiculo'  => 5, 'nombre' => 'CELDILLAS'],
            ['id' => 176, 'idClaseVehiculo'  => 2, 'nombre' => 'SUT'],
            ['id' => 999, 'idClaseVehiculo'  => 99, 'nombre' => 'SIN INFORMACION']


        ]);
    }
}
